DojoLoko/Controllers/TipoDeAssociacoesController.cs
using DojoLoko.Models;
using DojoLoko.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DojoLoko.Controllers
{
	public class TipoDeAssociacoesController : Controller
	{
		private ApplicationDbContext _context;

		public TipoDeAssociacoesController()
		{
			_context = new ApplicationDbContext();
		}

		protected override void Dispose(bool disposing)
		{
			_context.Dispose();
		}

        public ActionResult Index()
        {

            var associacoes = _context.TipodeAssociacao.ToList();
            if (User.IsInRole("CanManageCustomers"))
                return View(associacoes);
            return View("ReadOnlyIndex", associacoes);
        }

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Detalhes(int id)
        {
            var associacao = _context.TipodeAssociacao.SingleOrDefault(c => c.ID == id);

            if (associacao == null)
                return HttpNotFound();

            return View(associacao);

        }

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Editar(int id)
        {
            var associacao = _context.TipodeAssociacao.SingleOrDefault(c => c.ID == id);

            if (associacao == null)
                return HttpNotFound();

            var viewModel = new TipodeAssociacaoEditarViewModel
            {
               TipodeAssociacao = associacao
            };

            return View("Editar", viewModel);
        }

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Deletar(int id)
        {
            var associacao = _context.TipodeAssociacao.SingleOrDefault(c => c.ID == id);

            if (associacao == null)
                return HttpNotFound();

            _context.TipodeAssociacao.Remove(associacao);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost] // só será acessada com POST
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Salvar(TipoDeAssociacao associacao) // recebemos um cliente
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new TipodeAssociacaoEditarViewModel
                {
                    TipodeAssociacao = associacao
                };
                return View("Editar", viewModel);
            }

            if (associacao.ID == 0)
                _context.TipodeAssociacao.Add(associacao);
            else
            {
                var customerInDb = _context.TipodeAssociacao.Single(c => c.ID == associacao.ID);

                customerInDb.Nome = associacao.Nome;
                customerInDb.Mensalidade = associacao.Mensalidade;
                customerInDb.Periodo = associacao.Periodo;
            }
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Novo()
        {

            var viewModel = new TipodeAssociacaoEditarViewModel
            {
                TipodeAssociacao = new TipoDeAssociacao()
            };
            return View("Editar", viewModel);

        }
    }
}

DojoLoko/Views/TipoDeAssociacoes/Detalhes.cshtml
@model DojoLoko.Models.TipoDeAssociacao

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h2>@Model.Nome</h2>
    <p>Informações da associação:</p>
    <div class="row">
        <div class="col-sm-12">
            <p><span style="color: #317eac;">ID:</span> @Model.ID</p>
            <p><span style="color: #317eac;">Nome:</span> @Model.Nome</p>
            <p><span style="color: #317eac;">Periodo:</span> @Model.Periodo</p>
            <p><span style="color: #317eac;">Mensalidade:</span> R$@Model.Mensalidade</p>
        </div>
    </div>
</div>

DojoLoko/Views/TipoDeAssociacoes/Editar.cshtml
@model DojoLoko.ViewModels.TipodeAssociacaoEditarViewModel
@{
    ViewBag.Title = Model.Titulo;
}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Salvar", "TipoDeAssociacoes"))
{
    @Html.HiddenFor(m => m.TipodeAssociacao.ID)
    <div class="form-group">
        @Html.LabelFor(m => m.TipodeAssociacao.Nome)
        @Html.TextBoxFor(m => m.TipodeAssociacao.Nome, new { @class = "form-control" })
		@Html.ValidationMessageFor(m => m.TipodeAssociacao.Nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.TipodeAssociacao.Periodo)
        @Html.TextBoxFor(m => m.TipodeAssociacao.Periodo, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.TipodeAssociacao.Periodo)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.TipodeAssociacao.Mensalidade)
        @Html.TextBoxFor(m => m.TipodeAssociacao.Mensalidade, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.TipodeAssociacao.Mensalidade)
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
}

DojoLoko/Views/TipoDeAssociacoes/Index.cshtml
@model IEnumerable<DojoLoko.Models.TipoDeAssociacao>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Associações</h2></center>

@if (@Model.Any())
{
    <table class="table table-hover">
        <tbody>
            @foreach (var associacao in Model)
            {
                <tr>
                    <td style="vertical-align: middle;">
                        <a href="/TipoDeAssociacoes/Detalhes/@associacao.ID" style="width: 100%">@associacao.Nome</a>
                    </td>
                    <td style="vertical-align: middle;">
                        <a href="/TipoDeAssociacoes/Detalhes/@associacao.ID" style="width: 100%">@associacao.Periodo</a>
                    </td>
                    <td style="vertical-align: middle;">
                        <a href="/TipoDeAssociacoes/Detalhes/@associacao.ID" style="width: 100%">@associacao.Mensalidade</a>
                    </td>
                    <td class="col-md-2" style="vertical-align: middle;">
                        <a class="btn btn-primary" href="/TipoDeAssociacoes/Editar/@associacao.ID" style="width: 100%">Editar</a>
                    </td>
                    <td class="col-md-2" style="vertical-align: middle;">
                        <a class="btn btn-primary" href="/TipoDeAssociacoes/Deletar/@associacao.ID" style="width: 100%">Deletar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @Html.ActionLink("Nova associação", "Novo", null, new { @class = "btn btn-primary" })
}
else
{
    <p>Não temos nenhuma faixa cadastrada</p>
    <br />
    <br />
    @Html.ActionLink("Cadastrar", "Novo", null, new { @class = "btn btn-primary" })
}

DojoLoko/Views/TipoDeAssociacoes/ReadOnlyIndex.cshtml
@model IEnumerable<DojoLoko.Models.TipoDeAssociacao>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Associações</h2></center>

@if (@Model.Any())
{
    <table class="table table-hover">
        <tbody>
            @foreach (var associacao in Model)
            {
                <tr>
                    <td style="vertical-align: middle;">
                        @associacao.Nome
                    </td>
                    <td style="vertical-align: middle;">
                        @associacao.Periodo
                    </td>
                    <td style="vertical-align: middle;">
                        @associacao.Mensalidade
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não temos nenhuma faixa cadastrada</p>
}