DojoLoko/Models/Faixa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DojoLoko.Models
{
    public class Faixa
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Grau { get; set; }
    }
}

DojoLoko/Controllers/FaixasController.cs
using DojoLoko.Models;
using DojoLoko.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DojoLoko.Controllers
{
    public class FaixasController : Controller
    {

        private ApplicationDbContext _context;

        public FaixasController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult Index()
        {

            var faixas = _context.Faixa.ToList();
            if (User.IsInRole("CanManageCustomers"))
                return View(faixas);
            return View("ReadOnlyIndex", faixas);
        }

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Detalhes(int id)
        {
            var faixa = _context.Faixa.SingleOrDefault(c => c.ID == id);

            if (faixa == null)
                return HttpNotFound();

            return View(faixa);

        }

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Editar(int id)
        {
            var faixa = _context.Faixa.SingleOrDefault(c => c.ID == id);

            if (faixa == null)
                return HttpNotFound();

            var viewModel = new FaixaEditarViewModel
            {
                Faixa = faixa
            };

            return View("Editar", viewModel);
        }

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Deletar(int id)
        {
            var faixa = _context.Faixa.SingleOrDefault(c => c.ID == id);

            if (faixa == null)
                return HttpNotFound();

            _context.Faixa.Remove(faixa);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost] // só será acessada com POST
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Salvar(Faixa faixa) // recebemos um cliente
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new FaixaEditarViewModel
                {
                    Faixa = faixa
                };
                return View("Editar", viewModel);
            }

            if (faixa.ID == 0)
                _context.Faixa.Add(faixa);
            else
            {
                var customerInDb = _context.Faixa.Single(c => c.ID == faixa.ID);

                customerInDb.Nome = faixa.Nome;
                customerInDb.Grau = faixa.Grau;
            }
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Novo()
        {

            var viewModel = new FaixaEditarViewModel
            {
                Faixa = new Faixa()
            };
            return View("Editar", viewModel);

        }

    }
}

DojoLoko/Views/Faixas/Detalhes.cshtml
@model DojoLoko.Models.Faixa

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h2>@Model.Nome</h2>
    <p>Informações da faixa:</p>
    <div class="row">
        <div class="col-sm-12">
            <p><span style="color: #317eac;">ID:</span> @Model.ID</p>
            <p><span style="color: #317eac;">Nome:</span> @Model.Nome</p>
            <p><span style="color: #317eac;">Descrição:</span> @Model.Grau</p>
        </div>
    </div>
</div>

DojoLoko/Views/Faixas/Editar.cshtml
@model DojoLoko.ViewModels.FaixaEditarViewModel
@{
    ViewBag.Title = Model.Titulo;
}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Salvar", "Faixas"))
{
    @Html.HiddenFor(m => m.Faixa.ID)
    <div class="form-group">
        @Html.LabelFor(m => m.Faixa.Nome)
        @Html.TextBoxFor(m => m.Faixa.Nome, new { @class = "form-control" })
		@Html.ValidationMessageFor(m => m.Faixa.Nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Faixa.Grau)
        @Html.TextBoxFor(m => m.Faixa.Grau, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Faixa.Grau)
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
}

DojoLoko/Views/Faixas/Index.cshtml
@model IEnumerable<DojoLoko.Models.Faixa>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Faixas</h2></center>

@if (@Model.Any())
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr><th>Faixa</th></tr>
        </thead>
        <tbody>
            @foreach (var faixa in Model)
            {
                <tr><td>@Html.ActionLink(@faixa.Nome, "Detalhes", new { faixa.ID })</td></tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não temos nenhuma faixa cadastrado</p>
}

DojoLoko/Views/Faixas/ReadOnlyIndex.cshtml
@model IEnumerable<DojoLoko.Models.Faixa>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Faixas</h2></center>

@if (@Model.Any())
{
    <table class="table table-hover">
        <tbody>
            @foreach (var faixa in Model)
            {
                <tr>
                    <td style="vertical-align: middle;">
                        @faixa.Nome
                    </td>
                    <td class="col-md-2" style="vertical-align: middle;">
                        @faixa.Grau
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não temos nenhuma faixa cadastrada</p>
}