DojoLoko/Models/Aluno.cs
 using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DojoLoko.Models
{

    public class Aluno
    {
        public Aluno()
        {
            this.Aulas = new HashSet<Aula>();
        }
        public int ID { get; set; }
        public Faixa Faixa { get; set; }
        [Required]
        [Range(1,99)]
        public int FaixaId { get; set; }
        public TipoDeAssociacao TipoDeAssociacao { get; set; }
        [Required]
        [Range(1, 99)]
        public int TipodeAssociacaoId { get; set; }
        [Required]
        [StringLength(255)]
        [Display(Name = "Nome")]
        public string Nome { get; set; }
        [Required]
        [StringLength(255)]
        [Display(Name = "CPF")]
        public string CPF { get; set; }
        [Required]
        [StringLength(255)]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required]
        [StringLength(255)]
        [Display(Name = "Senha")]
        public string Senha { get; set; }
        public ICollection<Aula> Aulas { get; set; }
        public ICollection<int> AulasId { get; set; }
    }
}

DojoLoko/Controllers/AlunosController.cs
using DojoLoko.Models;
using DojoLoko.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DojoLoko.Controllers
{
	public class AlunosController : Controller
	{
		private ApplicationDbContext _context;

		public AlunosController()
		{
			_context = new ApplicationDbContext();
		}

		protected override void Dispose(bool disposing)
		{
			_context.Dispose();
		}

		public ActionResult Index()
		{
            var alunos = _context.Aluno.Include(c => c.Faixa).Include(c => c.TipoDeAssociacao).ToList();
            if (User.IsInRole("CanManageCustomers"))
                return View(alunos);
            return View("ReadOnlyIndex", alunos);
        }

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Detalhes(int id)
		{
			var aluno = _context.Aluno.Include(c => c.Faixa).Include(c => c.TipoDeAssociacao).Include(c => c.Aulas).SingleOrDefault(c => c.ID == id);

			if (aluno == null)
				return HttpNotFound();

			return View(aluno);

		}

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Editar(int id)
		{
			var aluno = _context.Aluno.Include(c => c.Faixa).Include(c => c.TipoDeAssociacao).Include(c => c.Aulas).SingleOrDefault(c => c.ID == id);

			if (aluno == null)
				return HttpNotFound();

			var viewModel = new AlunoEditarViewModel
			{
                Aluno = aluno,
                Faixa = _context.Faixa.ToList(),
                TipoDeAssociacao = _context.TipodeAssociacao.ToList(),
                Aula = _context.Aula.ToList()
            };

			return View("Editar", viewModel);
		}

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Deletar(int id)
        {
            var aluno = _context.Aluno.Include(c => c.Faixa).Include(c => c.TipoDeAssociacao).Include(c => c.Aulas).SingleOrDefault(c => c.ID == id);

            if (aluno == null)
                return HttpNotFound();

            _context.Aluno.Remove(aluno);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost] // só será acessada com POST
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Salvar(Aluno aluno) // recebemos um cliente
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new AlunoEditarViewModel
                {
                    Aluno = aluno,
                    Faixa = _context.Faixa.ToList(),
                    TipoDeAssociacao = _context.TipodeAssociacao.ToList(),
                    Aula = _context.Aula.ToList()
                };
                return View("Editar", viewModel);
            }

            if (aluno.ID == 0)
                _context.Aluno.Add(aluno);
            else
            {
                var customerInDb = _context.Aluno.Include(m => m.Aulas).Single(c => c.ID == aluno.ID);

                customerInDb.Nome = aluno.Nome;
                customerInDb.CPF = aluno.CPF;
                customerInDb.TipodeAssociacaoId = aluno.TipodeAssociacaoId;
                customerInDb.FaixaId = aluno.FaixaId;
                customerInDb.Aulas = aluno.Aulas;
            }
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Novo()
        {

            var viewModel = new AlunoEditarViewModel
            { 
                Aluno = new Aluno(),
                Faixa = _context.Faixa.ToList(),
                TipoDeAssociacao = _context.TipodeAssociacao.ToList(),
                Aula = _context.Aula.ToList()
            };
            return View("Editar", viewModel);

        }
	}
}

DojoLoko/Views/Alunos/Detalhes.cshtml
@model DojoLoko.Models.Aluno

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h2>@Model.Nome</h2>
    <p>Informações do aluno:</p>
    <div class="row">
        <div class="col-sm-12">
            <p><span style="color: #317eac;">ID:</span> @Model.ID</p>
            <p><span style="color: #317eac;">Nome:</span> @Model.Nome</p>
            <p><span style="color: #317eac;">CPF:</span> @Model.CPF</p>
            <p><span style="color: #317eac;">CPF:</span> @Model.Email</p>
            <p><span style="color: #317eac;">CPF:</span> @Model.Senha</p>
            <p><span style="color: #317eac;">Faixa:</span> @Model.Faixa.Nome</p>
            <p><span style="color: #317eac;">Tipo de associação:</span> @Model.TipoDeAssociacao.Nome</p>
            <p><span style="color: #317eac;">Aulas:</span></p>
            <ul>
                @foreach (var aula in Model.Aulas)
                {
                    <li>
                        <span style="color: #317eac;">ID:</span> @aula.ID<br />
                        <span style="color: #317eac;">Data:</span> @aula.Data
                    </li>
                }
            </ul>
        </div>
    </div>
</div>

DojoLoko/Views/Alunos/Editar.cshtml
@model DojoLoko.ViewModels.AlunoEditarViewModel
@{
    ViewBag.Title = Model.Titulo;
}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Salvar", "Alunos"))
{
    @Html.HiddenFor(m => m.Aluno.ID)
    <div class="form-group">
        @Html.LabelFor(m => m.Aluno.Nome)
        @Html.TextBoxFor(m => m.Aluno.Nome, new { @class = "form-control" })
		@Html.ValidationMessageFor(m => m.Aluno.Nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Aluno.CPF)
        @Html.TextBoxFor(m => m.Aluno.CPF, new { @class = "form-control" })
		@Html.ValidationMessageFor(m => m.Aluno.CPF)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Aluno.Email)
        @Html.TextBoxFor(m => m.Aluno.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Aluno.Email)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Aluno.Senha)
        @Html.TextBoxFor(m => m.Aluno.Senha, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Aluno.Senha)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Aluno.Faixa)
        @Html.DropDownListFor(m => m.Aluno.FaixaId, new SelectList(Model.Faixa, "ID", "Nome"), "Selecione uma faixa", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Aluno.FaixaId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Aluno.TipoDeAssociacao)
        @Html.DropDownListFor(m => m.Aluno.TipodeAssociacaoId, new SelectList(Model.TipoDeAssociacao, "ID", "Nome"), "Selecione um tipo de associação", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Aluno.TipodeAssociacaoId)
    </div>
    <div id="AulaAlunosTable">
        <table class="table table-bordered table-hover" id="tabela">
            <thead>
                <tr>
                    <th>Aulas</th>
                    <th style="text-align: center">#</th>
                </tr>
            </thead>
            <tbody>
                <tr id="lineClone">
                    <td>
                        <div class="form-group">
                            @Html.DropDownListFor(m => m.Aluno.AulasId, new SelectList(Model.Aula, "ID", "Data"), "Escolha", new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Aluno.Aulas)
                        </div>
                    </td>
                    <td><button data-AulaAlunos-id="@Model.Aluno.ID" class="btn btn-danger js-delete">Remover</button></td>
                </tr>
            </tbody>
        </table>
        <button type="button" class="btn btn-primary btnClone">Adicionar Linha</button>
    </div>
    <br /><br />
    <button type="submit" class="btn btn-primary">Salvar</button>
}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">

        $(".btnClone").click(function () {
            $("#lineClone").clone().appendTo("#tabela");
        });
        $("#tabela").on("click", ".js-delete",
            function () {
                var button = $(this);
                button.parents("tr").remove();
            });
    </script>
}

DojoLoko/Views/Alunos/Index.cshtml
@model IEnumerable<DojoLoko.Models.Aluno>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Alunos</h2></center>

@if (@Model.Any())
{
    <table class="table table-hover">
        <tbody>
            @foreach (var aluno in Model)
            {
               <tr>
                   <td style="vertical-align: middle;">
                        @Html.ActionLink(@aluno.Nome, "Detalhes", new { aluno.ID })
                   </td>
                   <td style="vertical-align: middle;">
                       @Html.ActionLink(@aluno.Faixa.Nome, "Detalhes", new { aluno.ID })
                   </td>
                   <td class="col-md-2" style="vertical-align: middle;">
                       <a class="btn btn-primary" href="/Alunos/Editar/@aluno.ID" style="width: 100%">Editar</a>
                   </td>
                   <td class="col-md-2" style="vertical-align: middle;">
                       <a class="btn btn-primary" href="/Alunos/Deletar/@aluno.ID" style="width: 100%">Deletar</a>
                   </td>
               </tr>                    
            }
            </tbody>
    </table>
    @Html.ActionLink("Novo aluno", "Novo", null, new { @class = "btn btn-primary"})
}
else
{
    <p>Não temos nenhum aluno cadastrado</p>
    <br />
    <br />
    @Html.ActionLink("Cadastrar", "Novo", null, new { @class = "btn btn-primary"})
}

DojoLoko/Views/Alunos/ReadOnlyIndex.cshtml
@model IEnumerable<DojoLoko.Models.Aluno>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Alunos</h2></center>

@if (@Model.Any())
{
    <table class="table table-hover">
        <tbody>
            @foreach (var aluno in Model)
            {
               <tr>
                   <td style="vertical-align: middle;">
                        @aluno.Nome
                   </td>
               </tr>                    
            }
            </tbody>
    </table>
}
else
{
    <p>Não temos nenhum aluno cadastrado</p>
}