DojoLoko/Models/Aula.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DojoLoko.Models
{

    public class Aula
    {
        public Aula()
        {
            this.Alunos = new HashSet<Aluno>();
        }
        public int ID { get; set; }
        public ICollection<Aluno> Alunos { get; set; }
        public ICollection<int> AlunosId { get; set; }
        public DateTime Data { get; set; }
    }
}

DojoLoko/Controllers/AulasController.cs
using DojoLoko.Models;
using DojoLoko.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DojoLoko.Controllers
{
	public class AulasController : Controller
	{
		private ApplicationDbContext _context;

		public AulasController()
		{
			_context = new ApplicationDbContext();
		}

		protected override void Dispose(bool disposing)
		{
			_context.Dispose();
		}

		public ActionResult Index()
		{
            var aulas = _context.Aula.Include(c => c.Alunos).ToList();
            if (User.IsInRole("CanManageCustomers"))
                return View(aulas);
            return View("ReadOnlyIndex", aulas);
        }

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Detalhes(int id)
		{
			var aula = _context.Aula.Include(c => c.Alunos).SingleOrDefault(c => c.ID == id);

			if (aula == null)
				return HttpNotFound();

			return View(aula);

		}

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Editar(int id)
		{
            var aula = _context.Aula.Include(c => c.Alunos).SingleOrDefault(c => c.ID == id);

            if (aula == null)
				return HttpNotFound();

            var viewModel = new AulaEditarViewModel
            {
                Aula = aula,
                Aluno = _context.Aluno.ToList()
			};

			return View("Editar", viewModel);
		}

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Deletar(int id)
        {
            var aula = _context.Aula.SingleOrDefault(c => c.ID == id);

            if (aula == null)
                return HttpNotFound();

            _context.Aula.Remove(aula);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost] // só será acessada com POST
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Salvar(Aula aula) // recebemos um cliente
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new AulaEditarViewModel
                {
                    Aula = aula,
                    Aluno = _context.Aluno.ToList()
                };
                return View("Editar", viewModel);
            }

            if (aula.ID == 0)
                _context.Aula.Add(aula);
            else
            {
                var customerInDb = _context.Aula.Include(c => c.Alunos).Single(c => c.ID == aula.ID);

                customerInDb.Alunos = aula.Alunos;
                customerInDb.Data = aula.Data;
            }
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Novo()
        {

            var viewModel = new AulaEditarViewModel
            { 
                Aula = new Aula(),
                Aluno = _context.Aluno.ToList()
            };
            return View("Editar", viewModel);

        }
	}
}

DojoLoko/Views/Aulas/Detalhes.cshtml
@model DojoLoko.Models.Aula

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h2>Aula @Model.Data</h2>
    <p>Informações da aula:</p>
    <div class="row">
        <div class="col-sm-12">
            <p><span style="color: #317eac;">ID:</span> @Model.ID</p>
            <p><span style="color: #317eac;">Data:</span> @Model.Data</p>
            <p><span style="color: #317eac;">Lista de alunos:</span></p>
            <ul>
                @foreach (var aula in Model.Alunos)
                {
                    <li>
                        <span style="color: #317eac;">ID:</span> @aula.ID<br />
                        <span style="color: #317eac;">Nome:</span> @aula.Nome
                    </li>
                }
            </ul>
        </div>
    </div>
</div>

DojoLoko/Views/Aulas/Editar.cshtml
@model DojoLoko.ViewModels.AulaEditarViewModel
@{
    ViewBag.Title = Model.Titulo;
}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Salvar", "Aulas"))
{
    @Html.HiddenFor(m => m.Aula.ID)
    <div class="form-group">
        @Html.LabelFor(m => m.Aula.Data)
        @Html.TextBoxFor(m => m.Aula.Data, new { @class = "form-control" })
		@Html.ValidationMessageFor(m => m.Aula.Data)
    </div>
    <div id="AulaAlunosTable">
        <table class="table table-bordered table-hover" id="tabela">
            <thead>
                <tr>
                    <th>Alunos</th>
                    <th style="text-align: center">#</th>
                </tr>
            </thead>
            <tbody>
                <tr id="lineClone">
                    <td>
                        <div class="form-group">
                            @Html.DropDownListFor(m => m.Aula.AlunosId, new SelectList(Model.Aluno, "ID", "Nome"), "Escolha", new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Aula.Alunos)
                        </div>
                    </td>
                    <td><button data-AulaAlunos-id="@Model.Aula.ID" class="btn btn-danger js-delete">Remover</button></td>
                </tr>
            </tbody>
        </table>
        <button type="button" class="btn btn-primary btnClone">Adicionar Linha</button>
    </div>
    <br /><br />
    <button type="submit" class="btn btn-primary">Salvar</button>
}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">

        $(".btnClone").click(function () {
            $("#lineClone").clone().appendTo("#tabela");
        });
        $("#tabela").on("click", ".js-delete",
            function () {
                var button = $(this);
                button.parents("tr").remove();
            });
    </script>
}

DojoLoko/Views/Aulas/Index.cshtml
@model IEnumerable<DojoLoko.Models.Aula>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Aulas</h2></center>

@if (@Model.Any())
{
    <table class="table table-hover">
        <tbody>
            @foreach (var aula in Model)
            {
               <tr>
                   <td style="vertical-align: middle;">
                       @aula.ID
                   </td>
                   <td style="vertical-align: middle;">
                        <a class="" href="/Aulas/Detalhes/@aula.ID" style="width: 100%">@aula.Data</a>
                   </td>
                   <td class="col-md-2" style="vertical-align: middle;">
                       <a class="btn btn-primary" href="/Aulas/Editar/@aula.ID" style="width: 100%">Editar</a>
                   </td>
                   <td class="col-md-2" style="vertical-align: middle;">
                       <a class="btn btn-primary" href="/Aulas/Deletar/@aula.ID" style="width: 100%">Deletar</a>
                   </td>
               </tr>                    
            }
            </tbody>
    </table>
    @Html.ActionLink("Nova aula", "Novo", null, new { @class = "btn btn-primary"})
}
else
{
    <p>Não temos nenhuma aula cadastrado</p>
    <br />
    <br />
    @Html.ActionLink("Cadastrar", "Novo", null, new { @class = "btn btn-primary"})
}

DojoLoko/Views/Aulas/ReadOnlyIndex.cshtml
@model IEnumerable<DojoLoko.Models.Aula>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Aulas</h2></center>

@if (@Model.Any())
{
    <table class="table table-hover">
        <tbody>
            @foreach (var aula in Model)
            {
               <tr>
                   <td style="vertical-align: middle;">
                        @aula.ID
                   </td>
                   <td style="vertical-align: middle;">
                       @aula.Data
                   </td>
               </tr>                    
            }
            </tbody>
    </table>
}
else
{
    <p>Não temos nenhum aluno cadastrado</p>
}